case_common:
  allureEpic: 标题：platform-Cloud-Plus微服务权限管理系统_接口文档
  allureFeature: 对象存储配置Controller
  allureStory: 新增对象存储配置
d:\PytestAutoApi\Files\Testcase\oss_01:
  host: ${{host()}}
  url: d:\PytestAutoApi\Files\Testcase\oss
  method: POST
  detail: 对象存储配置Controller - 新增对象存储配置
  headers:
    Authorization: $cache{app_token}
    Content-Language: zh_CN
    App-Source: WObird
  requestType: json
  is_run: null
  data:
    createBy: ''
    createTime: 0
    updateBy: ''
    updateTime: 0
    params: {}
    ossConfigId: 0
    configKey: ''
    accessKey: ''
    secretKey: ''
    bucketName: ''
    prefix: ''
    ossType: ''
    endpoint: ''
    domain: ''
    isHttps: ''
    status: ''
    region: ''
    ext1: ''
    remark: ''
    accessPolicy: ''
  dependence_case: false
  dependence_case_data: null
  assert:
    code:
      jsonpath: $.code
      type: ==
      value: 200
      AssertType: null
      message: 接口状态码不为200
    msg:
      jsonpath: $.msg
      type: contains
      value: 成功
      AssertType: null
  sql: null
  setup_sql: null
