case_common:
  allureEpic: 标题：platform-Cloud-Plus微服务权限管理系统_接口文档
  allureFeature: 云存储套餐规格
  allureStory: 根据typeId获取云存储套餐规格
product_storagePlanType_updatePlanSubByTypeId_01:
  host: ${{host()}}
  url: /product/storagePlanType/updatePlanSubByTypeId/$cache{typeId}
  method: POST
  detail: 云存储套餐规格 - 根据typeId获取云存储套餐规格
  headers:
    Authorization: $cache{app_token}
    Content-Language: zh_CN
    App-Source: WObird
  requestType: null
  is_run: null
  data: {}
  dependence_case: false
  dependence_case_data: null
  assert:
    code:
      jsonpath: $.code
      type: ==
      value: 200
      AssertType: null
      message: 接口状态码不为200
    msg:
      jsonpath: $.msg
      type: contains
      value: 成功
      AssertType: null
  sql: null
  setup_sql: null
