case_common:
  allureEpic: 标题：platform-Cloud-Plus微服务权限管理系统_接口文档
  allureFeature: 品牌品类（第2层）
  allureStory: 新增品牌品类
d:\PytestAutoApi\Files\Testcase\product_01:
  host: ${{host()}}
  url: d:\PytestAutoApi\Files\Testcase\product
  method: POST
  detail: 品牌品类（第2层） - 新增品牌品类
  headers:
    Authorization: $cache{app_token}
    Content-Language: zh_CN
    App-Source: WObird
  requestType: json
  is_run: null
  data:
    categoryId: ''
    name: ''
    egName: ''
    remark: ''
    appSource: ''
  dependence_case: false
  dependence_case_data: null
  assert:
    code:
      jsonpath: $.code
      type: ==
      value: 200
      AssertType: null
      message: 接口状态码不为200
    msg:
      jsonpath: $.msg
      type: contains
      value: 成功
      AssertType: null
  sql: null
  setup_sql: null
