case_common:
  allureEpic: 标题：platform-Cloud-Plus微服务权限管理系统_接口文档
  allureFeature: 套餐功能
  allureStory: 新增套餐功能
d:\PytestAutoApi\Files\Testcase\product_01:
  host: ${{host()}}
  url: d:\PytestAutoApi\Files\Testcase\product
  method: POST
  detail: 套餐功能 - 新增套餐功能
  headers:
    Authorization: $cache{app_token}
    Content-Language: zh_CN
    App-Source: WObird
  requestType: json
  is_run: null
  data:
    createBy: ''
    createTime: 0
    updateBy: ''
    updateTime: 0
    params: {}
    planId: 0
    appSource: ''
    sourceType: ''
    planName: ''
    planMultiName: ''
    videoStorageType: ''
    videoStorageDuration: 0
    planShareDevice: 0
    applePayGoodId: ''
    googlePayGoodId: ''
    planStatus: ''
    sort: 0
    planTypeNameListVo:
      names: []
    putOnShelves: ''
  dependence_case: false
  dependence_case_data: null
  assert:
    code:
      jsonpath: $.code
      type: ==
      value: 200
      AssertType: null
      message: 接口状态码不为200
    msg:
      jsonpath: $.msg
      type: contains
      value: 成功
      AssertType: null
  sql: null
  setup_sql: null
