case_common:
  allureEpic: 标题：platform-Cloud-Plus微服务权限管理系统_接口文档
  allureFeature: 云存储订单
  allureStory: 新增云存储订单
d:\PytestAutoApi\Files\Testcase\product_01:
  host: ${{host()}}
  url: d:\PytestAutoApi\Files\Testcase\product
  method: POST
  detail: 云存储订单 - 新增云存储订单
  headers:
    Authorization: $cache{app_token}
    Content-Language: zh_CN
    App-Source: WObird
  requestType: json
  is_run: null
  data:
    createBy: ''
    createTime: 0
    updateBy: ''
    updateTime: 0
    params: {}
    orderId: 0
    orderNo: ''
    payNo: ''
    payRefundNo: ''
    orderType: ''
    planName: ''
    planMultiName: ''
    planId: 0
    planTypeId: 0
    userId: ''
    usePlanId: 0
    orderPrice: {}
    payPlate: 0
    payType: 0
    payStatus: 0
    refundStatus: 0
    orderStatus: 0
    orderTime: 0
    payTime: 0
    refundTime: 0
    orderBeginTime: 0
    orderEndTime: 0
    planShareDevice: 0
    planTypeName: ''
    planTypeMultiName: ''
    paymentToken: ''
    planPrice: {}
    orderCount: 0
    freeLabel: 0
  dependence_case: false
  dependence_case_data: null
  assert:
    code:
      jsonpath: $.code
      type: ==
      value: 200
      AssertType: null
      message: 接口状态码不为200
    msg:
      jsonpath: $.msg
      type: contains
      value: 成功
      AssertType: null
  sql: null
  setup_sql: null
