case_common:
  allureEpic: 标题：platform-Cloud-Plus微服务权限管理系统_接口文档
  allureFeature: 3固件ota升级相关接口
  allureStory: 新增固件ota升级
d:\PytestAutoApi\Files\Testcase\product_01:
  host: ${{host()}}
  url: d:\PytestAutoApi\Files\Testcase\product
  method: POST
  detail: 3固件ota升级相关接口 - 新增固件ota升级
  headers:
    Authorization: $cache{app_token}
    Content-Language: zh_CN
    App-Source: WObird
  requestType: json
  is_run: null
  data:
    createBy: ''
    createTime: 0
    updateBy: ''
    updateTime: 0
    params: {}
    id: 0
    productId: ''
    firmwareInfoId: 0
    firmwareVersionId: 0
    upgradeManner: 0
    upgradeDesc: ''
    multiNameJson: ''
    multiNameList: []
    awaitUpgradeVersion: ''
    awaitUpgradeVersionList: []
    awaitUpgradeArea: ''
    awaitUpgradeAreaList: []
    publish: 0
  dependence_case: false
  dependence_case_data: null
  assert:
    code:
      jsonpath: $.code
      type: ==
      value: 200
      AssertType: null
      message: 接口状态码不为200
    msg:
      jsonpath: $.msg
      type: contains
      value: 成功
      AssertType: null
  sql: null
  setup_sql: null
