case_common:
  allureEpic: 标题：platform-Cloud-Plus微服务权限管理系统_接口文档
  allureFeature: 产品
  allureStory: 产品发布(立即发布)
product_product_productPublish_01:
  host: ${{host()}}
  url: /product/product/productPublish
  method: PUT
  detail: 产品 - 产品发布(立即发布)
  headers:
    Authorization: $cache{app_token}
    Content-Language: zh_CN
    App-Source: WObird
  requestType: params
  is_run: null
  data:
    productId: $cache{productId}
  dependence_case: false
  dependence_case_data: null
  assert:
    code:
      jsonpath: $.code
      type: ==
      value: 200
      AssertType: null
      message: 接口状态码不为200
    msg:
      jsonpath: $.msg
      type: contains
      value: 成功
      AssertType: null
  sql: null
  setup_sql: null
