case_common:
  allureEpic: 标题：platform-Cloud-Plus微服务权限管理系统_接口文档
  allureFeature: 已激活设备控制器
  allureStory: 获取设备属性（影子属性）
product_device_getDevShadowProps_01:
  host: ${{host()}}
  url: /product/device/getDevShadowProps
  method: GET
  detail: 已激活设备控制器 - 获取设备属性（影子属性）
  headers:
    Authorization: $cache{app_token}
    Content-Language: zh_CN
    App-Source: WObird
  requestType: params
  is_run: null
  data:
    productId: $cache{productId}
    devId: $cache{devId}
  dependence_case: false
  dependence_case_data: null
  assert:
    code:
      jsonpath: $.code
      type: ==
      value: 200
      AssertType: null
      message: 接口状态码不为200
    msg:
      jsonpath: $.msg
      type: contains
      value: 成功
      AssertType: null
  sql: null
  setup_sql: null
