case_common:
  allureEpic: 标题：platform-Cloud-Plus微服务权限管理系统_接口文档
  allureFeature: 已激活设备控制器
  allureStory: 查询设备列表
product_device_list_01:
  host: ${{host()}}
  url: /product/device/list
  method: POST
  detail: 已激活设备控制器 - 查询设备列表
  headers:
    Authorization: $cache{app_token}
    Content-Language: zh_CN
    App-Source: WObird
  requestType: json
  is_run: null
  data:
    pageQuery:
      pageSize: 0
      pageNum: 0
      orderByColumn: ''
      isAsc: ''
    paramData:
      devId: ''
      name: ''
      uuid: ''
      type: 0
      timezone: ''
      userId: ''
      productId: ''
      bv: ''
      serviceArea: ''
      online: 0
      isShare: true
      linkType: 0
      devUtcTimeZone: ''
      ipcType: ''
  dependence_case: false
  dependence_case_data: null
  assert:
    code:
      jsonpath: $.code
      type: ==
      value: 200
      AssertType: null
      message: 接口状态码不为200
    msg:
      jsonpath: $.msg
      type: contains
      value: 成功
      AssertType: null
  sql: null
  setup_sql: null
