case_common:
  allureEpic: 标题：platform-Cloud-Plus微服务权限管理系统_接口文档
  allureFeature: app版本升级配置 APP升级配置模块
  allureStory: 编辑版本
system_config_updateVersion_01:
  host: ${{host()}}
  url: /system/config/updateVersion
  method: POST
  detail: app版本升级配置 APP升级配置模块 - 编辑版本
  headers:
    Authorization: $cache{app_token}
    Content-Language: zh_CN
    App-Source: WObird
  requestType: json
  is_run: null
  data:
    appVersionUpgradeId: 0
    systemType: 0
    versionId: 0
    versionNumber: ''
    upgradeManner: 0
    versionDescMulti: []
    appType: 0
  dependence_case: false
  dependence_case_data: null
  assert:
    code:
      jsonpath: $.code
      type: ==
      value: 200
      AssertType: null
      message: 接口状态码不为200
    msg:
      jsonpath: $.msg
      type: contains
      value: 成功
      AssertType: null
  sql: null
  setup_sql: null
