case_common:
  allureEpic: 标题：iot-data-center后台管理系统_接口文档
  allureFeature: 对象存储配置
  allureStory: 获取对象存储配置详细信息
system_oss_config_01:
  host: ${{host()}}
  url: /system/oss/config/$cache{ossConfigId}
  method: GET
  detail: 对象存储配置 - 获取对象存储配置详细信息
  headers:
    Authorization: $cache{app_token}
    Content-Language: zh_CN
    App-Source: WObird
  requestType: null
  is_run: null
  data: {}
  dependence_case: false
  dependence_case_data: null
  assert:
    code:
      jsonpath: $.code
      type: ==
      value: 200
      AssertType: null
      message: 接口状态码不为200
    msg:
      jsonpath: $.msg
      type: contains
      value: 成功
      AssertType: null
  sql: null
  setup_sql: null
