case_common:
  allureEpic: 标题：platform-Cloud-Plus微服务权限管理系统_接口文档
  allureFeature: 产品
  allureStory: 固件配置列表(发布固件配置)
product_product_firmwareConfig_publish_01:
  host: ${{host()}}
  url: /product/product/firmwareConfig/publish
  method: POST
  detail: 产品 - 固件配置列表(发布固件配置)
  headers:
    Authorization: $cache{app_token}
    Content-Language: zh_CN
    App-Source: WObird
  requestType: json
  is_run: null
  data:
    productId: ''
    firmwareInfoId: []
  dependence_case: false
  dependence_case_data: null
  assert:
    code:
      jsonpath: $.code
      type: ==
      value: 200
      AssertType: null
      message: 接口状态码不为200
    msg:
      jsonpath: $.msg
      type: contains
      value: 成功
      AssertType: null
  sql: null
  setup_sql: null
