pipeline {
    agent any
    stages {
        stage('Print WorkSpace') {
            steps {
                script{
                    echo "Hello world"
                    echo "当前的工作目录: ${env.WORKSPACE}"
                }
            }
        }
        stage('准备 Python 环境') {
            steps {
                script {
                def venvExists = fileExists('venv/bin/activate')
                if (!venvExists) {
                    echo "未检测到虚拟环境，创建并安装依赖"
                    sh '''
                        python3 -m venv venv
                        . venv/bin/activate
                        
                    '''
                } else {
                    echo "虚拟环境已存在，跳过安装"
                }
                
                }

            steps {
                script {
                    sh 'pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple'
                }
            }
            }
        }
        stage('执行python脚本'){
            steps {
                script{
                    sh "python3 ${env.WORKSPACE}/redis_main.py"
                }
            }
        }
    }
}