case_common:
  allureEpic: 标题：platform-Cloud-Plus微服务权限管理系统_接口文档
  allureFeature: 消息code与模板类型关系
  allureStory: 查询消息code与类型关系列表
product_operate_codeTypeShip_list_01:
  host: ${{host()}}
  url: /product/operate/codeTypeShip/list
  method: GET
  detail: 消息code与模板类型关系 - 查询消息code与类型关系列表
  headers:
    Authorization: $cache{app_token}
    Content-Language: zh_CN
    App-Source: WObird
  requestType: params
  is_run: null
  data:
    bo: $cache{bo}
  dependence_case: false
  dependence_case_data: null
  assert:
    code:
      jsonpath: $.code
      type: ==
      value: 200
      AssertType: null
      message: 接口状态码不为200
    msg:
      jsonpath: $.msg
      type: contains
      value: 成功
      AssertType: null
  sql: null
  setup_sql: null
