# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: assignNet.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61ssignNet.proto\"a\n\x10\x41ssignNetRequest\x12\x1b\n\x06\x64\x65vice\x18\x01 \x01(\x0b\x32\x0b.DeviceInfo\x12\x0c\n\x04time\x18\x02 \x01(\x03\x12\x0f\n\x07\x61uthKey\x18\x03 \x01(\t\x12\x11\n\trequestId\x18\x04 \x01(\t\"T\n\x11\x41ssignNetResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x0f\n\x07\x61uthKey\x18\x03 \x01(\t\x12\x11\n\trequestId\x18\x04 \x01(\t\"\xca\x02\n\nDeviceInfo\x12\x0e\n\x06taskId\x18\x01 \x01(\t\x12\x0e\n\x06homeId\x18\x02 \x01(\t\x12\x10\n\x08\x64\x65viceId\x18\x03 \x01(\t\x12\x0c\n\x04uuid\x18\x04 \x01(\t\x12\x11\n\tproductId\x18\x05 \x01(\t\x12\x0b\n\x03uid\x18\x06 \x01(\t\x12\r\n\x05\x61ppId\x18\x07 \x01(\t\x12\x0e\n\x06ipaddr\x18\x08 \x01(\t\x12\x0f\n\x07\x64\x65vName\x18\t \x01(\t\x12\x10\n\x08timezone\x18\n \x01(\t\x12\x0b\n\x03lat\x18\x0b \x01(\x01\x12\x0b\n\x03lon\x18\x0c \x01(\x01\x12\x0e\n\x06\x66mvVer\x18\r \x01(\t\x12\x0e\n\x06socVer\x18\x0e \x01(\t\x12\x0e\n\x06mcuVer\x18\x0f \x01(\t\x12\x13\n\x0bwirelessVer\x18\x10 \x01(\t\x12\x10\n\x08language\x18\x11 \x01(\t\x12\x13\n\x0bserviceArea\x18\x12 \x01(\t\x12\x14\n\x0cipclicenseId\x18\x13 \x01(\tB/\n com.szlongzy.common.protobuf.dtoB\x0b\x41ssignNetVob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'assignNet_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n com.szlongzy.common.protobuf.dtoB\013AssignNetVo'
  _ASSIGNNETREQUEST._serialized_start=19
  _ASSIGNNETREQUEST._serialized_end=116
  _ASSIGNNETRESPONSE._serialized_start=118
  _ASSIGNNETRESPONSE._serialized_end=202
  _DEVICEINFO._serialized_start=205
  _DEVICEINFO._serialized_end=535
# @@protoc_insertion_point(module_scope)
