# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: birdOssEvent.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x62irdOssEvent.proto\"\xf9\x01\n\x0b\x42irdEventVo\x12\x10\n\x08objDevId\x18\x01 \x01(\t\x12\x0f\n\x07\x65ventId\x18\x02 \x01(\t\x12\r\n\x05\x66type\x18\x03 \x01(\x05\x12\r\n\x05\x65type\x18\x04 \x01(\t\x12\x11\n\tlableJson\x18\x05 \x01(\t\x12\x0f\n\x07osstype\x18\x06 \x01(\x05\x12\x0b\n\x03url\x18\x07 \x01(\t\x12\x0c\n\x04iLen\x18\x08 \x01(\x05\x12\x0e\n\x06zeroTm\x18\t \x01(\x03\x12\x0e\n\x06TmZone\x18\n \x01(\t\x12\x10\n\x08\x64uration\x18\x0b \x01(\x05\x12\x11\n\tisEncrypt\x18\x0c \x01(\x08\x12\x12\n\nencryptKey\x18\r \x01(\t\x12\x11\n\tlocalfile\x18\x0e \x01(\tB0\n com.szlongzy.common.protobuf.dtoB\x0c\x42irdOssEventb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'birdOssEvent_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n com.szlongzy.common.protobuf.dtoB\014BirdOssEvent'
  _BIRDEVENTVO._serialized_start=23
  _BIRDEVENTVO._serialized_end=272
# @@protoc_insertion_point(module_scope)
