# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: checkModel.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63heckModel.proto\"D\n\x11\x43heckModelRequest\x12\x10\n\x08objDevId\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\x03\x12\x0f\n\x07\x61uthKey\x18\x03 \x01(\t\"X\n\x12\x43heckModelResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x0f\n\x07\x61uthKey\x18\x03 \x01(\t\x12\x14\n\x04\x64\x61ta\x18\x04 \x03(\x0b\x32\x06.codes\"\x15\n\x05\x63odes\x12\x0c\n\x04\x63ode\x18\x01 \x03(\tB0\n com.szlongzy.common.protobuf.dtoB\x0c\x43heckModelVob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'checkModel_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n com.szlongzy.common.protobuf.dtoB\014CheckModelVo'
  _CHECKMODELREQUEST._serialized_start=20
  _CHECKMODELREQUEST._serialized_end=88
  _CHECKMODELRESPONSE._serialized_start=90
  _CHECKMODELRESPONSE._serialized_end=178
  _CODES._serialized_start=180
  _CODES._serialized_end=201
# @@protoc_insertion_point(module_scope)
