# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cmdPro.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import modelType_pb2 as modelType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63mdPro.proto\x1a\x0fmodelType.proto\"\x88\x01\n\rCmdProRequest\x12\x10\n\x08objDevId\x18\x01 \x01(\t\x12\x17\n\x06optype\x18\x02 \x01(\x0e\x32\x07.opType\x12\x15\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x07.dataVo\x12\x0f\n\x07\x61uthKey\x18\x04 \x01(\t\x12\x11\n\tproductId\x18\x05 \x01(\t\x12\x11\n\trequestId\x18\x06 \x01(\t\"\xa6\x01\n\x0e\x43mdProResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x10\n\x08objDevId\x18\x02 \x01(\t\x12\x17\n\x06optype\x18\x03 \x01(\x0e\x32\x07.opType\x12\x15\n\x04\x64\x61ta\x18\x04 \x01(\x0b\x32\x07.dataVo\x12\x0b\n\x03msg\x18\x05 \x01(\t\x12\x0f\n\x07\x61uthKey\x18\x06 \x01(\t\x12\x11\n\tproductId\x18\x07 \x01(\t\x12\x11\n\trequestId\x18\x08 \x01(\t\"?\n\x06\x64\x61taVo\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x18\n\x04type\x18\x02 \x01(\x0e\x32\n.ModelType\x12\r\n\x05value\x18\x03 \x01(\t*#\n\x06opType\x12\x0b\n\x07\x43ommand\x10\x00\x12\x0c\n\x08Property\x10\x01\x42-\n com.szlongzy.common.protobuf.dtoB\tCmdPropVob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cmdPro_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n com.szlongzy.common.protobuf.dtoB\tCmdPropVo'
  _OPTYPE._serialized_start=406
  _OPTYPE._serialized_end=441
  _CMDPROREQUEST._serialized_start=34
  _CMDPROREQUEST._serialized_end=170
  _CMDPRORESPONSE._serialized_start=173
  _CMDPRORESPONSE._serialized_end=339
  _DATAVO._serialized_start=341
  _DATAVO._serialized_end=404
# @@protoc_insertion_point(module_scope)
