# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: devEventUp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import modelType_pb2 as modelType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x64\x65vEventUp.proto\x1a\x0fmodelType.proto\"\xb3\x01\n\x07\x45ventVo\x12\x10\n\x08objDevId\x18\x01 \x01(\t\x12\x0f\n\x07\x65ventId\x18\x02 \x01(\t\x12\r\n\x05\x65type\x18\x03 \x01(\t\x12\x0e\n\x06picUrl\x18\x04 \x01(\t\x12\x11\n\tlocalfile\x18\x05 \x01(\t\x12\x0b\n\x03msg\x18\x06 \x01(\t\x12\x0e\n\x06zeroTm\x18\x07 \x01(\x03\x12\x0e\n\x06TmZone\x18\x08 \x01(\t\x12\x12\n\nis_encrypt\x18\t \x01(\x08\x12\x12\n\nencryptKey\x18\n \x01(\t\"\xbc\x01\n\nOssEventVo\x12\x10\n\x08objDevId\x18\x01 \x01(\t\x12\x0f\n\x07\x65ventId\x18\x02 \x01(\t\x12\x0f\n\x07osstype\x18\x03 \x01(\t\x12\x0e\n\x06ossUrl\x18\x04 \x01(\t\x12\x0e\n\x06zeroTm\x18\x05 \x01(\x03\x12\x0e\n\x06TmZone\x18\x06 \x01(\t\x12\x10\n\x08\x64uration\x18\x07 \x01(\x05\x12\x12\n\nis_encrypt\x18\x08 \x01(\x08\x12\x12\n\nencryptKey\x18\t \x01(\t\x12\x10\n\x08videoLen\x18\n \x01(\x05\"\xb1\x01\n\x0c\x41larmEventVo\x12\x10\n\x08objDevId\x18\x01 \x01(\t\x12\x0f\n\x07\x65ventId\x18\x02 \x01(\t\x12\x11\n\talarmType\x18\x03 \x01(\t\x12\x18\n\x04\x64\x61ta\x18\x04 \x01(\x0b\x32\n.AlarmData\x12\x0e\n\x06zeroTm\x18\x05 \x01(\x03\x12\x0e\n\x06TmZone\x18\x06 \x01(\t\x12\x0e\n\x06userId\x18\x07 \x01(\t\x12\x0f\n\x07\x64\x65vName\x18\x08 \x01(\t\x12\x10\n\x08jsonInfo\x18\t \x01(\t\"\x94\x01\n\tAlarmData\x12\x11\n\tmodelCode\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x1c\n\x08\x63odeType\x18\x03 \x01(\x0e\x32\n.ModelType\x12\"\n\tcondition\x18\x04 \x01(\x0e\x32\x0f.AlarmCondition\x12\x16\n\x0ethresholdValue\x18\x05 \x01(\t\x12\x0b\n\x03msg\x18\x06 \x01(\t*M\n\x0e\x41larmCondition\x12\t\n\x05other\x10\x00\x12\x06\n\x02\x65q\x10\x01\x12\x06\n\x02gt\x10\x02\x12\x06\n\x02lt\x10\x03\x12\x07\n\x03gte\x10\x04\x12\x07\n\x03lte\x10\x05\x12\x06\n\x02in\x10\x06\x42\x30\n com.szlongzy.common.protobuf.dtoB\x0c\x44\x65vEventUpVob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'devEventUp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n com.szlongzy.common.protobuf.dtoB\014DevEventUpVo'
  _ALARMCONDITION._serialized_start=741
  _ALARMCONDITION._serialized_end=818
  _EVENTVO._serialized_start=38
  _EVENTVO._serialized_end=217
  _OSSEVENTVO._serialized_start=220
  _OSSEVENTVO._serialized_end=408
  _ALARMEVENTVO._serialized_start=411
  _ALARMEVENTVO._serialized_end=588
  _ALARMDATA._serialized_start=591
  _ALARMDATA._serialized_end=739
# @@protoc_insertion_point(module_scope)
