# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: deviceProp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import modelType_pb2 as modelType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x64\x65viceProp.proto\x1a\x0fmodelType.proto\"C\n\nPropDataVo\x12\x18\n\x04type\x18\x01 \x01(\x0e\x32\n.ModelType\x12\r\n\x05value\x18\x02 \x01(\t\x12\x0c\n\x04time\x18\x03 \x01(\x03\x42*\n com.szlongzy.common.protobuf.dtoB\x06PropVob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'deviceProp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n com.szlongzy.common.protobuf.dtoB\006PropVo'
  _PROPDATAVO._serialized_start=37
  _PROPDATAVO._serialized_end=104
# @@protoc_insertion_point(module_scope)
