# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: firmwareVersion.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66irmwareVersion.proto\"3\n\x0eVersionRequest\x12\x10\n\x08objDevId\x18\x01 \x01(\t\x12\x0f\n\x07\x61uthKey\x18\x02 \x01(\t\"s\n\x0fVersionResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x10\n\x08objDevId\x18\x02 \x01(\t\x12\x0b\n\x03msg\x18\x03 \x01(\t\x12\x0f\n\x07\x61uthKey\x18\x04 \x01(\t\x12 \n\x04\x64\x61ta\x18\x05 \x01(\x0b\x32\x12.FirmwareVersionVo\"i\n\x11\x46irmwareVersionVo\x12\x0e\n\x06\x66mvVer\x18\x01 \x01(\t\x12\x0e\n\x06socVer\x18\x02 \x01(\t\x12\x0e\n\x06mcuVer\x18\x03 \x01(\t\x12\x13\n\x0bwirelessVer\x18\x04 \x01(\t\x12\x0f\n\x07standby\x18\x05 \x01(\tB1\n com.szlongzy.common.protobuf.dtoB\rFirmwareVerVob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'firmwareVersion_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n com.szlongzy.common.protobuf.dtoB\rFirmwareVerVo'
  _VERSIONREQUEST._serialized_start=25
  _VERSIONREQUEST._serialized_end=76
  _VERSIONRESPONSE._serialized_start=78
  _VERSIONRESPONSE._serialized_end=193
  _FIRMWAREVERSIONVO._serialized_start=195
  _FIRMWAREVERSIONVO._serialized_end=300
# @@protoc_insertion_point(module_scope)
