# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: generalBuffData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15generalBuffData.proto\"N\n\x0fGeneralBuffData\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0c\n\x04\x62uff\x18\x02 \x01(\t\x12\x0c\n\x04time\x18\x03 \x01(\x03\x12\x11\n\trequestId\x18\x04 \x01(\tB5\n com.szlongzy.common.protobuf.dtoB\x11GeneralBuffDataVob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'generalBuffData_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n com.szlongzy.common.protobuf.dtoB\021GeneralBuffDataVo'
  _GENERALBUFFDATA._serialized_start=25
  _GENERALBUFFDATA._serialized_end=103
# @@protoc_insertion_point(module_scope)
