# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modelFunction.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import modelType_pb2 as modelType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13modelFunction.proto\x1a\x0fmodelType.proto\"\x8e\x02\n\rModelFunction\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0e\n\x06\x65gName\x18\x02 \x01(\t\x12\x0e\n\x06\x63nName\x18\x03 \x01(\t\x12\x18\n\x04type\x18\x04 \x01(\x0e\x32\n.ModelType\x12\n\n\x02\x64\x62\x18\x05 \x01(\x05\x12\x0f\n\x07saveLog\x18\x06 \x01(\x08\x12\x1b\n\x08\x62oolfunc\x18\x07 \x01(\x0b\x32\t.BoolFunc\x12\x1d\n\tfloatfunc\x18\x08 \x01(\x0b\x32\n.FloatFunc\x12\x19\n\x07intfunc\x18\t \x01(\x0b\x32\x08.IntFunc\x12\x1b\n\x08\x65numfunc\x18\n \x01(\x0b\x32\t.EnumFunc\x12$\n\x0bstrjsonfunc\x18\x0b \x01(\x0b\x32\x0f.StringJsonFunc\"S\n\x08\x42oolFunc\x12\x1e\n\x04list\x18\x01 \x03(\x0b\x32\x10.BoolFunc.BoolVo\x1a\'\n\x06\x42oolVo\x12\r\n\x05value\x18\x01 \x01(\x08\x12\x0e\n\x06readme\x18\x02 \x01(\t\"V\n\x08\x45numFunc\x12 \n\x05range\x18\x01 \x03(\x0b\x32\x11.EnumFunc.RangeVo\x1a(\n\x07RangeVo\x12\r\n\x05value\x18\x01 \x01(\t\x12\x0e\n\x06readme\x18\x02 \x01(\t\"N\n\x07IntFunc\x12\x0c\n\x04unit\x18\x01 \x01(\t\x12\x0b\n\x03min\x18\x02 \x01(\x05\x12\x0b\n\x03max\x18\x03 \x01(\x05\x12\r\n\x05scale\x18\x04 \x01(\x05\x12\x0c\n\x04step\x18\x05 \x01(\x05\"]\n\tFloatFunc\x12\x0c\n\x04unit\x18\x01 \x01(\t\x12\x0b\n\x03min\x18\x02 \x01(\x01\x12\x0b\n\x03max\x18\x03 \x01(\x01\x12\r\n\x05scale\x18\x04 \x01(\x01\x12\x0c\n\x04step\x18\x05 \x01(\x01\x12\x0b\n\x03\x62it\x18\x06 \x01(\x05\"/\n\x0eStringJsonFunc\x12\r\n\x05value\x18\x01 \x01(\t\x12\x0e\n\x06readme\x18\x02 \x01(\tB3\n com.szlongzy.common.protobuf.dtoB\x0fModelFunctionVob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'modelFunction_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n com.szlongzy.common.protobuf.dtoB\017ModelFunctionVo'
  _MODELFUNCTION._serialized_start=41
  _MODELFUNCTION._serialized_end=311
  _BOOLFUNC._serialized_start=313
  _BOOLFUNC._serialized_end=396
  _BOOLFUNC_BOOLVO._serialized_start=357
  _BOOLFUNC_BOOLVO._serialized_end=396
  _ENUMFUNC._serialized_start=398
  _ENUMFUNC._serialized_end=484
  _ENUMFUNC_RANGEVO._serialized_start=444
  _ENUMFUNC_RANGEVO._serialized_end=484
  _INTFUNC._serialized_start=486
  _INTFUNC._serialized_end=564
  _FLOATFUNC._serialized_start=566
  _FLOATFUNC._serialized_end=659
  _STRINGJSONFUNC._serialized_start=661
  _STRINGJSONFUNC._serialized_end=708
# @@protoc_insertion_point(module_scope)
