# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ntpTime.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rntpTime.proto\"T\n\nNtpRespose\x12\x16\n\x0e\x64\x65viceSendTime\x18\x01 \x01(\x03\x12\x16\n\x0eserverRecvTime\x18\x02 \x01(\x03\x12\x16\n\x0eserverSendTime\x18\x03 \x01(\x03\"$\n\nNtpRequest\x12\x16\n\x0e\x64\x65viceSendTime\x18\x01 \x01(\x03\x42+\n com.szlongzy.common.protobuf.dtoB\x07NtpTimeb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ntpTime_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n com.szlongzy.common.protobuf.dtoB\007NtpTime'
  _NTPRESPOSE._serialized_start=17
  _NTPRESPOSE._serialized_end=101
  _NTPREQUEST._serialized_start=103
  _NTPREQUEST._serialized_end=139
# @@protoc_insertion_point(module_scope)
