# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: productModel.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import modelFunction_pb2 as modelFunction__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12productModel.proto\x1a\x13modelFunction.proto\"]\n\x0cProductModel\x12!\n\tmodelFunc\x18\x01 \x01(\x0b\x32\x0e.ModelFunction\x12\n\n\x02up\x18\x02 \x01(\x08\x12\x0c\n\x04\x64own\x18\x03 \x01(\x08\x12\x10\n\x08isCustom\x18\x04 \x01(\x08\x42\x32\n com.szlongzy.common.protobuf.dtoB\x0eProductModelVob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'productModel_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n com.szlongzy.common.protobuf.dtoB\016ProductModelVo'
  _PRODUCTMODEL._serialized_start=43
  _PRODUCTMODEL._serialized_end=136
# @@protoc_insertion_point(module_scope)
