# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reboot.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0creboot.proto\"?\n\rrebootRequest\x12\x10\n\x08objDevId\x18\x01 \x01(\t\x12\x0f\n\x07\x61uthKey\x18\x02 \x01(\t\x12\x0b\n\x03uid\x18\x03 \x01(\t\"?\n\x0erebootResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x10\n\x08objDevId\x18\x02 \x01(\t\x12\x0b\n\x03msg\x18\x03 \x01(\tB,\n com.szlongzy.common.protobuf.dtoB\x08RebootVob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reboot_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n com.szlongzy.common.protobuf.dtoB\010RebootVo'
  _REBOOTREQUEST._serialized_start=16
  _REBOOTREQUEST._serialized_end=79
  _REBOOTRESPONSE._serialized_start=81
  _REBOOTRESPONSE._serialized_end=144
# @@protoc_insertion_point(module_scope)
