# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shadowProSet.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import modelType_pb2 as modelType__pb2
import cmdPro_pb2 as cmdPro__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12shadowProSet.proto\x1a\x0fmodelType.proto\x1a\x0c\x63mdPro.proto\"2\n\rShadowRequest\x12\x10\n\x08objDevId\x18\x01 \x01(\t\x12\x0f\n\x07\x61uthKey\x18\x02 \x01(\t\"b\n\x0eShadowResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x10\n\x08objDevId\x18\x02 \x01(\t\x12\x0b\n\x03msg\x18\x03 \x01(\t\x12\x0f\n\x07\x61uthKey\x18\x04 \x01(\t\x12\x10\n\x08jsonData\x18\x05 \x01(\tB3\n com.szlongzy.common.protobuf.dtoB\x0fShadowPropSetVob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shadowProSet_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n com.szlongzy.common.protobuf.dtoB\017ShadowPropSetVo'
  _SHADOWREQUEST._serialized_start=53
  _SHADOWREQUEST._serialized_end=103
  _SHADOWRESPONSE._serialized_start=105
  _SHADOWRESPONSE._serialized_end=203
# @@protoc_insertion_point(module_scope)
