case_common:
  allureEpic: 标题：platform-Cloud-Plus微服务权限管理系统_接口文档
  allureFeature: 问题反馈
  allureStory: ''
product_feedback_userIssue_platformContinueFeedback_01:
  host: ${{host()}}
  url: /product/feedback/userIssue/platformContinueFeedback/$cache{platformReplyType}
  method: POST
  detail: '问题反馈 - '
  headers:
    Authorization: $cache{app_token}
    Content-Language: zh_CN
    App-Source: WObird
  requestType: json
  is_run: null
  data:
    feedbackId: ''
    imageUrlList: []
    videoUrlList: []
    feedbackContent: ''
  dependence_case: false
  dependence_case_data: null
  assert:
    code:
      jsonpath: $.code
      type: ==
      value: 200
      AssertType: null
      message: 接口状态码不为200
    msg:
      jsonpath: $.msg
      type: contains
      value: 成功
      AssertType: null
  sql: null
  setup_sql: null
