case_common:
  allureEpic: 标题：platform-Cloud-Plus微服务权限管理系统_接口文档
  allureFeature: 品牌品类与标准模型关系
  allureStory: 批量新增标准模型和品牌品类关系
product_modelStandardCategory_addBatch_01:
  host: ${{host()}}
  url: /product/modelStandardCategory/addBatch
  method: POST
  detail: 品牌品类与标准模型关系 - 批量新增标准模型和品牌品类关系
  headers:
    Authorization: $cache{app_token}
    Content-Language: zh_CN
    App-Source: WObird
  requestType: json
  is_run: null
  data:
    modelCode: ''
    ids: []
  dependence_case: false
  dependence_case_data: null
  assert:
    code:
      jsonpath: $.code
      type: ==
      value: 200
      AssertType: null
      message: 接口状态码不为200
    msg:
      jsonpath: $.msg
      type: contains
      value: 成功
      AssertType: null
  sql: null
  setup_sql: null
