case_common:
  allureEpic: 标题：platform-Cloud-Plus微服务权限管理系统_接口文档
  allureFeature: 产品与指令模型关系
  allureStory: 更新产品，更新不为null对象
product_productModel_editSet_01:
  host: ${{host()}}
  url: /product/productModel/editSet
  method: PUT
  detail: 产品与指令模型关系 - 更新产品，更新不为null对象
  headers:
    Authorization: $cache{app_token}
    Content-Language: zh_CN
    App-Source: WObird
  requestType: json
  is_run: null
  data:
    id: 0
    productId: ''
    modelCode: ''
    upStatus: true
    downStatus: true
    cnName: ''
    egName: ''
    saveLog: true
    isCustom: true
    isPublish: true
    type: ''
    remark: ''
    dataFunc: {}
    dmsType: 0
  dependence_case: false
  dependence_case_data: null
  assert:
    code:
      jsonpath: $.code
      type: ==
      value: 200
      AssertType: null
      message: 接口状态码不为200
    msg:
      jsonpath: $.msg
      type: contains
      value: 成功
      AssertType: null
  sql: null
  setup_sql: null
