case_common:
  allureEpic: 标题：platform-Cloud-Plus微服务权限管理系统_接口文档
  allureFeature: 1固件信息控相关接口
  allureStory: 新增固件信息产品下拉列表
product_firmwareInfo_firmwareProductList_01:
  host: ${{host()}}
  url: /product/firmwareInfo/firmwareProductList
  method: POST
  detail: 1固件信息控相关接口 - 新增固件信息产品下拉列表
  headers:
    Authorization: $cache{app_token}
    Content-Language: zh_CN
    App-Source: WObird
  requestType: params
  is_run: null
  data: {}
  dependence_case: false
  dependence_case_data: null
  assert:
    code:
      jsonpath: $.code
      type: ==
      value: 200
      AssertType: null
      message: 接口状态码不为200
    msg:
      jsonpath: $.msg
      type: contains
      value: 成功
      AssertType: null
  sql: null
  setup_sql: null
