case_common:
  allureEpic: 标题：platform-Cloud-Plus微服务权限管理系统_接口文档
  allureFeature: 品牌品类（第2层）
  allureStory: 根据appSource 查询产品id
product_brandCategory_getProductByAppSource_01:
  host: ${{host()}}
  url: /product/brandCategory/getProductByAppSource/$cache{appSource}
  method: GET
  detail: 品牌品类（第2层） - 根据appSource 查询产品id
  headers:
    Authorization: $cache{app_token}
    Content-Language: zh_CN
    App-Source: WObird
  requestType: null
  is_run: null
  data: {}
  dependence_case: false
  dependence_case_data: null
  assert:
    code:
      jsonpath: $.code
      type: ==
      value: 200
      AssertType: null
      message: 接口状态码不为200
    msg:
      jsonpath: $.msg
      type: contains
      value: 成功
      AssertType: null
  sql: null
  setup_sql: null
