case_common:
  allureEpic: 标题：platform-Cloud-Plus微服务权限管理系统_接口文档
  allureFeature: 产品与指令模型关系
  allureStory: 取消发布单条产品与指令模型关系
product_productModel_func_cancel_01:
  host: ${{host()}}
  url: /product/productModel/func/cancel
  method: PUT
  detail: 产品与指令模型关系 - 取消发布单条产品与指令模型关系
  headers:
    Authorization: $cache{app_token}
    Content-Language: zh_CN
    App-Source: WObird
  requestType: params
  is_run: null
  data:
    productId: $cache{productId}
    modelCode: $cache{modelCode}
  dependence_case: false
  dependence_case_data: null
  assert:
    code:
      jsonpath: $.code
      type: ==
      value: 200
      AssertType: null
      message: 接口状态码不为200
    msg:
      jsonpath: $.msg
      type: contains
      value: 成功
      AssertType: null
  sql: null
  setup_sql: null
