case_common:
  allureEpic: 标题：platform-Cloud-Plus微服务权限管理系统_接口文档
  allureFeature: 固件版本功能关联控制器
  allureStory: 查询版本已关联的功能productModel id列表
product_versionFunc_queryVersionFunc_01:
  host: ${{host()}}
  url: /product/versionFunc/queryVersionFunc/$cache{firmwareVersionId}
  method: GET
  detail: 固件版本功能关联控制器 - 查询版本已关联的功能productModel id列表
  headers:
    Authorization: $cache{app_token}
    Content-Language: zh_CN
    App-Source: WObird
  requestType: null
  is_run: null
  data: {}
  dependence_case: false
  dependence_case_data: null
  assert:
    code:
      jsonpath: $.code
      type: ==
      value: 200
      AssertType: null
      message: 接口状态码不为200
    msg:
      jsonpath: $.msg
      type: contains
      value: 成功
      AssertType: null
  sql: null
  setup_sql: null
