case_common:
  allureEpic: 标题：platform-Cloud-Plus微服务权限管理系统_接口文档
  allureFeature: 知识文章
  allureStory: 删除知识文章
d:\PytestAutoApi\Files\Testcase\knowledgeArticle_01:
  host: ${{host()}}
  url: d:\PytestAutoApi\Files\Testcase\knowledgeArticle
  method: DELETE
  detail: 知识文章 - 删除知识文章
  headers:
    Authorization: $cache{app_token}
    Content-Language: zh_CN
    App-Source: WObird
  requestType: null
  is_run: null
  data: {}
  dependence_case: false
  dependence_case_data: null
  assert:
    code:
      jsonpath: $.code
      type: ==
      value: 200
      AssertType: null
      message: 接口状态码不为200
    msg:
      jsonpath: $.msg
      type: contains
      value: 成功
      AssertType: null
  sql: null
  setup_sql: null
