case_common:
  allureEpic: 标题：platform-Cloud-Plus微服务权限管理系统_接口文档
  allureFeature: 知识文章
  allureStory: 查询产品类型列表统计知识
product_knowledge_knowledgeArticle_productKnowledgeList_01:
  host: ${{host()}}
  url: /product/knowledge/knowledgeArticle/productKnowledgeList
  method: POST
  detail: 知识文章 - 查询产品类型列表统计知识
  headers:
    Authorization: $cache{app_token}
    Content-Language: zh_CN
    App-Source: WObird
  requestType: json
  is_run: null
  data:
    pageQuery:
      pageSize: 0
      pageNum: 0
      orderByColumn: ''
      isAsc: ''
    paramData:
      customerId: ''
      categoryId: ''
      typeId: ''
      typeName: ''
      productName: ''
  dependence_case: false
  dependence_case_data: null
  assert:
    code:
      jsonpath: $.code
      type: ==
      value: 200
      AssertType: null
      message: 接口状态码不为200
    msg:
      jsonpath: $.msg
      type: contains
      value: 成功
      AssertType: null
  sql: null
  setup_sql: null
