case_common:
  allureEpic: 标题：platform-Cloud-Plus微服务权限管理系统_接口文档
  allureFeature: 宠物食谱
  allureStory: 统一新增宠物食谱
product_pet_dietary_wholeAdd_01:
  host: ${{host()}}
  url: /product/pet/dietary/wholeAdd
  method: POST
  detail: 宠物食谱 - 统一新增宠物食谱
  headers:
    Authorization: $cache{app_token}
    Content-Language: zh_CN
    App-Source: WObird
  requestType: json
  is_run: null
  data:
    dietaryBo:
      dietaryId: ''
      cnName: ''
      egName: ''
      jaName: ''
      deName: ''
      hkName: ''
      petTypes: []
      effects: []
      isPublish: true
      isShelve: true
      picIdList: []
    foodBo:
      id: 0
      dietaryId: ''
      quantity: 0
      unit: ''
      totalWeight: {}
      carbonWater: {}
      heatQuantity: {}
      protein: {}
      fat: {}
      salt: {}
      fiber: {}
      remark: ''
      foodDetails: []
    labelBo:
      id: 0
      dietaryId: ''
      rawCook: ''
      type: ''
      tasteList: []
      difficulty: ''
      preference: ''
      ageAppropriateList: []
      demandList: []
    stepBo:
      steps: []
    noteBo:
      dietaryId: ''
      cnText: ''
      egText: ''
      jaText: ''
      deText: ''
      hkText: ''
      number: 0
    authorBo:
      id: 0
      dietaryId: ''
      cnName: ''
      egName: ''
      url: ''
      bucketName: ''
      fileName: ''
  dependence_case: false
  dependence_case_data: null
  assert:
    code:
      jsonpath: $.code
      type: ==
      value: 200
      AssertType: null
      message: 接口状态码不为200
    msg:
      jsonpath: $.msg
      type: contains
      value: 成功
      AssertType: null
  sql: null
  setup_sql: null
