case_common:
  allureEpic: 标题：platform-Cloud-Plus微服务权限管理系统_接口文档
  allureFeature: 宠物食谱
  allureStory: 新增宠物食谱 :返回食谱id
product_pet_dietary_add_01:
  host: ${{host()}}
  url: /product/pet/dietary/add
  method: POST
  detail: 宠物食谱 - 新增宠物食谱 :返回食谱id
  headers:
    Authorization: $cache{app_token}
    Content-Language: zh_CN
    App-Source: WObird
  requestType: json
  is_run: null
  data:
    dietaryId: ''
    cnName: ''
    egName: ''
    jaName: ''
    deName: ''
    hkName: ''
    petTypes: []
    effects: []
    isPublish: true
    isShelve: true
    picIdList: []
  dependence_case: false
  dependence_case_data: null
  assert:
    code:
      jsonpath: $.code
      type: ==
      value: 200
      AssertType: null
      message: 接口状态码不为200
    msg:
      jsonpath: $.msg
      type: contains
      value: 成功
      AssertType: null
  sql: null
  setup_sql: null
