case_common:
  allureEpic: 标题：platform-Cloud-Plus微服务权限管理系统_接口文档
  allureFeature: 宠物食谱
  allureStory: 上传食谱图片
product_pet_dietary_upfile_01:
  host: ${{host()}}
  url: /product/pet/dietary/upfile
  method: POST
  detail: 宠物食谱 - 上传食谱图片
  headers:
    Authorization: $cache{app_token}
    Content-Language: zh_CN
    App-Source: WObird
  requestType: json
  is_run: null
  data:
    picFile: ''
    number: 0
  dependence_case: false
  dependence_case_data: null
  assert:
    code:
      jsonpath: $.code
      type: ==
      value: 200
      AssertType: null
      message: 接口状态码不为200
    msg:
      jsonpath: $.msg
      type: contains
      value: 成功
      AssertType: null
  sql: null
  setup_sql: null
