case_common:
  allureEpic: 标题：platform-Cloud-Plus微服务权限管理系统_接口文档
  allureFeature: 套餐功能
  allureStory: 查询关联套餐规格的套餐类别
product_cloudStoragePlan_getPlanlist_01:
  host: ${{host()}}
  url: /product/cloudStoragePlan/getPlanlist
  method: GET
  detail: 套餐功能 - 查询关联套餐规格的套餐类别
  headers:
    Authorization: $cache{app_token}
    Content-Language: zh_CN
    App-Source: WObird
  requestType: params
  is_run: null
  data:
    bo: $cache{bo}
    pageQuery: $cache{pageQuery}
  dependence_case: false
  dependence_case_data: null
  assert:
    code:
      jsonpath: $.code
      type: ==
      value: 200
      AssertType: null
      message: 接口状态码不为200
    msg:
      jsonpath: $.msg
      type: contains
      value: 成功
      AssertType: null
  sql: null
  setup_sql: null
