case_common:
  allureEpic: 标题：platform-Cloud-Plus微服务权限管理系统_接口文档
  allureFeature: app设备控制
  allureStory: app获取配网是否成功
appdevice_info_appDevice_getConfigureNetwork_01:
  host: ${{host()}}
  url: /appdevice/info/appDevice/getConfigureNetwork
  method: GET
  detail: app设备控制 - app获取配网是否成功
  headers:
    Authorization: $cache{app_token}
    Content-Language: zh_CN
    App-Source: WObird
  requestType: params
  is_run: null
  data:
    taskId: $cache{taskId}
  dependence_case: false
  dependence_case_data: null
  assert:
    code:
      jsonpath: $.code
      type: ==
      value: 200
      AssertType: null
      message: 接口状态码不为200
    msg:
      jsonpath: $.msg
      type: contains
      value: 成功
      AssertType: null
  sql: null
  setup_sql: null
