case_common:
  allureEpic: 标题：platform-Cloud-Plus微服务权限管理系统_接口文档
  allureFeature: 参数配置 信息操作处理
  allureStory: 根据参数键名查询参数值
system_config_configKey_01:
  host: ${{host()}}
  url: /system/config/configKey/$cache{configKey}
  method: GET
  detail: 参数配置 信息操作处理 - 根据参数键名查询参数值
  headers:
    Authorization: $cache{app_token}
    Content-Language: zh_CN
    App-Source: WObird
  requestType: null
  is_run: null
  data: {}
  dependence_case: false
  dependence_case_data: null
  assert:
    code:
      jsonpath: $.code
      type: ==
      value: 200
      AssertType: null
      message: 接口状态码不为200
    msg:
      jsonpath: $.msg
      type: contains
      value: 成功
      AssertType: null
  sql: null
  setup_sql: null
