openapi: 3.0.1
info:
  title: 标题：platform-Cloud-Plus微服务权限管理系统_接口文档
  description: 描述：微服务权限管理系统, 具体包括XXX,XXX模块...
  contact:
    name: lzyiot
    url: https://szlongzy.com
    email: lzyiot@szlongzy.com
  version: 版本号：系统版本...
servers:
- url: http://172.10.21.16:9204
  description: Generated server url
security:
- apiKey: []
tags:
- name: 对象存储配置Controller
  description: 对象存储配置Controller
- name: 文件上传 控制层
  description: 文件上传 控制层
- name: 短信功能
  description: 短信功能
- name: HeartBeat
  description: HeartBeat
- name: 邮件功能
  description: 邮件功能
paths:
  /resource/oss/config:
    put:
      tags:
      - 对象存储配置Controller
      summary: 修改对象存储配置
      description: 修改对象存储配置
      operationId: edit
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SysOssConfigBo'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/RVoid'
    post:
      tags:
      - 对象存储配置Controller
      summary: 新增对象存储配置
      description: 新增对象存储配置
      operationId: add
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SysOssConfigBo'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/RVoid'
  /resource/oss/config/changeStatus:
    put:
      tags:
      - 对象存储配置Controller
      summary: 状态修改
      description: 状态修改
      operationId: changeStatus
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SysOssConfigBo'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/RVoid'
  /resource/oss/upload:
    post:
      tags:
      - 文件上传 控制层
      summary: 上传OSS对象存储
      description: 上传OSS对象存储
      operationId: upload
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
              - file
              type: object
              properties:
                file:
                  type: string
                  description: 文件
                  format: binary
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/RMapStringString'
  /resource/sms/code:
    get:
      tags:
      - 短信功能
      summary: 短信验证码
      description: 短信验证码
      operationId: smsCaptcha
      parameters:
      - name: phonenumber
        in: query
        description: 用户手机号
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/RVoid'
  /resource/oss/list:
    get:
      tags:
      - 文件上传 控制层
      summary: 查询OSS对象存储列表
      description: 查询OSS对象存储列表
      operationId: list
      parameters:
      - name: bo
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/SysOssBo'
      - name: pageQuery
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/PageQuery'
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TableDataInfoSysOssVo'
  /resource/oss/listByIds/{ossIds}:
    get:
      tags:
      - 文件上传 控制层
      summary: 查询OSS对象基于id串
      description: 查询OSS对象基于id串
      operationId: listByIds
      parameters:
      - name: ossIds
        in: path
        description: OSS对象ID串
        required: true
        schema:
          type: array
          items:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/RListSysOssVo'
  /resource/oss/download/{ossId}:
    get:
      tags:
      - 文件上传 控制层
      summary: 下载OSS对象存储
      description: 下载OSS对象存储
      operationId: download
      parameters:
      - name: ossId
        in: path
        description: OSS对象ID
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
  /resource/oss/config/{ossConfigId}:
    get:
      tags:
      - 对象存储配置Controller
      summary: 获取对象存储配置详细信息
      description: 获取对象存储配置详细信息
      operationId: getInfo
      parameters:
      - name: ossConfigId
        in: path
        description: OSS配置ID
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/RSysOssConfigVo'
  /resource/oss/config/list:
    get:
      tags:
      - 对象存储配置Controller
      summary: 查询对象存储配置列表
      description: 查询对象存储配置列表
      operationId: list_1
      parameters:
      - name: bo
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/SysOssConfigBo'
      - name: pageQuery
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/PageQuery'
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TableDataInfoSysOssConfigVo'
  /resource/heartBeat:
    get:
      tags:
      - HeartBeat
      summary: HeartBeat
      description: HeartBeat
      operationId: heartBeat
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/RVoid'
  /resource/email/code:
    get:
      tags:
      - 邮件功能
      summary: 邮箱验证码
      description: 邮箱验证码
      operationId: emailCode
      parameters:
      - name: email
        in: query
        description: 邮箱
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/RVoid'
  /resource/oss/{ossIds}:
    delete:
      tags:
      - 文件上传 控制层
      summary: 删除OSS对象存储
      description: 删除OSS对象存储
      operationId: remove
      parameters:
      - name: ossIds
        in: path
        description: OSS对象ID串
        required: true
        schema:
          type: array
          items:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/RVoid'
  /resource/oss/config/{ossConfigIds}:
    delete:
      tags:
      - 对象存储配置Controller
      summary: 删除对象存储配置
      description: 删除对象存储配置
      operationId: remove_1
      parameters:
      - name: ossConfigIds
        in: path
        description: OSS配置ID串
        required: true
        schema:
          type: array
          items:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/RVoid'
components:
  schemas:
    SysOssConfigBo:
      required:
      - accessKey
      - accessPolicy
      - bucketName
      - configKey
      - endpoint
      - ossConfigId
      - secretKey
      type: object
      properties:
        createBy:
          type: string
          description: 创建者
        createTime:
          type: integer
          description: 创建时间
          format: int64
        updateBy:
          type: string
          description: 更新者
        updateTime:
          type: integer
          description: 更新时间
          format: int64
        params:
          type: object
          additionalProperties:
            type: object
          description: 请求参数
        ossConfigId:
          type: integer
          description: 主建
          format: int64
        configKey:
          maxLength: 100
          minLength: 2
          type: string
          description: 配置key
        accessKey:
          maxLength: 100
          minLength: 2
          type: string
          description: accessKey
        secretKey:
          maxLength: 100
          minLength: 2
          type: string
          description: 秘钥
        bucketName:
          maxLength: 100
          minLength: 2
          type: string
          description: 桶名称
        prefix:
          type: string
          description: 前缀
        ossType:
          type: string
          description: 服务商类型，例如：minio,aws,oracle
        endpoint:
          maxLength: 100
          minLength: 2
          type: string
          description: 访问站点
        domain:
          type: string
          description: 自定义域名
        isHttps:
          type: string
          description: 是否https（Y=是,N=否）
        status:
          type: string
          description: 是否默认（0=是,1=否）
        region:
          type: string
          description: 域
        ext1:
          type: string
          description: 扩展字段
        remark:
          type: string
          description: 备注
        accessPolicy:
          type: string
          description: 桶权限类型(0private 1public 2custom)
      description: 对象存储配置业务对象 sys_oss_config
    RVoid:
      type: object
      properties:
        code:
          type: integer
          description: 消息状态码(470,校验errorcode, 提示msg多语言内容, 500:app直接提示服务异常)
          format: int32
        msg:
          type: string
          description: 消息内容  多语言message 仅状态码470有效, 其他为前端自己多语言
        data:
          type: object
          description: 数据对象
        paramMsg:
          type: object
          additionalProperties:
            type: object
          description: "参数校验返回对象(给web使用, app不用)\n 示例: {\"字段名\": \"提示消息\"}\n {\"userName\"\
            : \"用户名已存在,请重新输入\"}"
        errCode:
          type: integer
          description: 仅状态码470有效校验errorcode
          format: int32
      description: 响应信息主体
    RMapStringString:
      type: object
      properties:
        code:
          type: integer
          description: 消息状态码(470,校验errorcode, 提示msg多语言内容, 500:app直接提示服务异常)
          format: int32
        msg:
          type: string
          description: 消息内容  多语言message 仅状态码470有效, 其他为前端自己多语言
        data:
          type: object
          additionalProperties:
            type: string
          description: 数据对象
        paramMsg:
          type: object
          additionalProperties:
            type: object
          description: "参数校验返回对象(给web使用, app不用)\n 示例: {\"字段名\": \"提示消息\"}\n {\"userName\"\
            : \"用户名已存在,请重新输入\"}"
        errCode:
          type: integer
          description: 仅状态码470有效校验errorcode
          format: int32
      description: 响应信息主体
    SysOssBo:
      type: object
      properties:
        createBy:
          type: string
          description: 创建者
        createTime:
          type: integer
          description: 创建时间
          format: int64
        updateBy:
          type: string
          description: 更新者
        updateTime:
          type: integer
          description: 更新时间
          format: int64
        params:
          type: object
          additionalProperties:
            type: object
          description: 请求参数
        ossId:
          type: integer
          description: ossId
          format: int64
        fileName:
          type: string
          description: 文件名
        originalName:
          type: string
          description: 原名
        fileSuffix:
          type: string
          description: 文件后缀名
        url:
          type: string
          description: URL地址
        service:
          type: string
          description: 服务商
      description: OSS对象存储分页查询对象 sys_oss
    PageQuery:
      type: object
      properties:
        pageSize:
          type: integer
          description: 分页大小
          format: int32
        pageNum:
          minimum: 1
          type: integer
          description: 当前页数
          format: int32
        orderByColumn:
          type: string
          description: 排序列
        isAsc:
          type: string
          description: "排序的方向desc或者asc\n 支持的用法如下:\n {isAsc:\"asc\",orderByColumn:\"\
            id\"} order by id asc\n {isAsc:\"asc\",orderByColumn:\"id,createTime\"\
            } order by id asc,create_time asc\n {isAsc:\"desc\",orderByColumn:\"id,createTime\"\
            } order by id desc,create_time desc\n {isAsc:\"asc,desc\",orderByColumn:\"\
            id,createTime\"} order by id asc,create_time desc"
      description: 分页查询实体类
    SysOssVo:
      type: object
      properties:
        ossId:
          type: integer
          description: 对象存储主键
          format: int64
        fileName:
          type: string
          description: 文件名
        originalName:
          type: string
          description: 原名
        fileSuffix:
          type: string
          description: 文件后缀名
        url:
          type: string
          description: URL地址
        createTime:
          type: string
          description: 创建时间
          format: date-time
        createBy:
          type: string
          description: 上传人
        service:
          type: string
          description: 服务商
      description: OSS对象存储视图对象 sys_oss
    TableDataInfoSysOssVo:
      type: object
      properties:
        pageSize:
          type: integer
          description: 分页大小
          format: int64
        pageNum:
          type: integer
          description: 当前页数
          format: int64
        totalPage:
          type: integer
          description: 总页数
          format: int64
        total:
          type: integer
          description: 总记录数
          format: int64
        rows:
          type: array
          description: 列表数据
          items:
            $ref: '#/components/schemas/SysOssVo'
        code:
          type: integer
          description: 消息状态码
          format: int32
        msg:
          type: string
          description: 消息内容
      description: 表格分页数据对象
    RListSysOssVo:
      type: object
      properties:
        code:
          type: integer
          description: 消息状态码(470,校验errorcode, 提示msg多语言内容, 500:app直接提示服务异常)
          format: int32
        msg:
          type: string
          description: 消息内容  多语言message 仅状态码470有效, 其他为前端自己多语言
        data:
          type: array
          description: 数据对象
          items:
            $ref: '#/components/schemas/SysOssVo'
        paramMsg:
          type: object
          additionalProperties:
            type: object
          description: "参数校验返回对象(给web使用, app不用)\n 示例: {\"字段名\": \"提示消息\"}\n {\"userName\"\
            : \"用户名已存在,请重新输入\"}"
        errCode:
          type: integer
          description: 仅状态码470有效校验errorcode
          format: int32
      description: 响应信息主体
    RSysOssConfigVo:
      type: object
      properties:
        code:
          type: integer
          description: 消息状态码(470,校验errorcode, 提示msg多语言内容, 500:app直接提示服务异常)
          format: int32
        msg:
          type: string
          description: 消息内容  多语言message 仅状态码470有效, 其他为前端自己多语言
        data:
          $ref: '#/components/schemas/SysOssConfigVo'
        paramMsg:
          type: object
          additionalProperties:
            type: object
          description: "参数校验返回对象(给web使用, app不用)\n 示例: {\"字段名\": \"提示消息\"}\n {\"userName\"\
            : \"用户名已存在,请重新输入\"}"
        errCode:
          type: integer
          description: 仅状态码470有效校验errorcode
          format: int32
      description: 响应信息主体
    SysOssConfigVo:
      type: object
      properties:
        ossConfigId:
          type: integer
          description: 主建
          format: int64
        configKey:
          type: string
          description: 配置key
        accessKey:
          type: string
          description: accessKey
        secretKey:
          type: string
          description: 秘钥
        bucketName:
          type: string
          description: 桶名称
        prefix:
          type: string
          description: 前缀
        ossType:
          type: string
          description: 服务商类型，例如：minio,aws,oracle
        endpoint:
          type: string
          description: 访问站点
        domain:
          type: string
          description: 自定义域名
        isHttps:
          type: string
          description: 是否https（Y=是,N=否）
        region:
          type: string
          description: 域
        status:
          type: string
          description: 是否默认（0=是,1=否）
        ext1:
          type: string
          description: 扩展字段
        remark:
          type: string
          description: 备注
        accessPolicy:
          type: string
          description: 桶权限类型(0private 1public 2custom)
      description: 对象存储配置视图对象 sys_oss_config
    TableDataInfoSysOssConfigVo:
      type: object
      properties:
        pageSize:
          type: integer
          description: 分页大小
          format: int64
        pageNum:
          type: integer
          description: 当前页数
          format: int64
        totalPage:
          type: integer
          description: 总页数
          format: int64
        total:
          type: integer
          description: 总记录数
          format: int64
        rows:
          type: array
          description: 列表数据
          items:
            $ref: '#/components/schemas/SysOssConfigVo'
        code:
          type: integer
          description: 消息状态码
          format: int32
        msg:
          type: string
          description: 消息内容
      description: 表格分页数据对象
  securitySchemes:
    apiKey:
      type: apiKey
      name: Authorization
      in: header
