case_common:
  allureEpic: 标题：platform-Cloud-Plus微服务权限管理系统_接口文档
  allureFeature: 公共上传接口
  allureStory: 通用文件上传接口
product_upload_common_uploadPublic_01:
  host: ${{host()}}
  url: /product/upload/common/uploadPublic
  method: POST
  detail: 公共上传接口 - 通用文件上传接口
  headers:
    Authorization: $cache{app_token}
    Content-Language: zh_CN
    App-Source: WObird
  requestType: json
  is_run: null
  data:
    fileBusType: ''
    multipartFile: ''
    fileMd5Str: ''
  dependence_case: false
  dependence_case_data: null
  assert:
    code:
      jsonpath: $.code
      type: ==
      value: 200
      AssertType: null
      message: 接口状态码不为200
    msg:
      jsonpath: $.msg
      type: contains
      value: 成功
      AssertType: null
  sql: null
  setup_sql: null
