case_common:
  allureEpic: 标题：platform-Cloud-Plus微服务权限管理系统_接口文档
  allureFeature: 标准指令模型功能点
  allureStory: 插入bool类型指令模型功能点
product_modelFunction_addBoolFunc_01:
  host: ${{host()}}
  url: /product/modelFunction/addBoolFunc
  method: POST
  detail: 标准指令模型功能点 - 插入bool类型指令模型功能点
  headers:
    Authorization: $cache{app_token}
    Content-Language: zh_CN
    App-Source: WObird
  requestType: json
  is_run: null
  data:
    code: ''
    cnName: ''
    egName: ''
    saveLog: true
    isPublish: true
    upStatus: true
    downStatus: true
    isConfTemplate: true
    type: ''
    dataFunc:
      btrue:
        remark: ''
      bfalse:
        remark: ''
    remark: ''
  dependence_case: false
  dependence_case_data: null
  assert:
    code:
      jsonpath: $.code
      type: ==
      value: 200
      AssertType: null
      message: 接口状态码不为200
    msg:
      jsonpath: $.msg
      type: contains
      value: 成功
      AssertType: null
  sql: null
  setup_sql: null
