case_common:
  allureEpic: 标题：platform-Cloud-Plus微服务权限管理系统_接口文档
  allureFeature: banner配置信息
  allureStory: 新增banner配置信息
d:\PytestAutoApi\Files\Testcase\system_01:
  host: ${{host()}}
  url: d:\PytestAutoApi\Files\Testcase\system
  method: POST
  detail: banner配置信息 - 新增banner配置信息
  headers:
    Authorization: $cache{app_token}
    Content-Language: zh_CN
    App-Source: WObird
  requestType: json
  is_run: null
  data:
    createBy: ''
    createTime: 0
    updateBy: ''
    updateTime: 0
    params: {}
    appBannerConfigInfoId: 0
    bannerId: ''
    bannerType: ''
    bannerName: ''
    appSource: ''
    parentUserId: 0
    bannerImageUrl: ''
    startTime: 0
    endTime: 0
    countDownStartTime: 0
    countDownEndTime: 0
    sort: 0
    jumpPageType: 0
    jumpPagePath: ''
    jumpPageShare: 0
    systemTypeAndroid: 0
    androidVersionId: 0
    systemTypeIos: 0
    iosVersionId: 0
    bannerScope: 0
    putOnShelves: 0
    remark: ''
    bannerCountryCodeList: []
    bannerPetConfig:
      petTypeList: []
      petWeightMin: 0
      petWeightMax: 0
      petQuantityMin: 0
      petQuantityMax: 0
    bannerProductConfig:
      whetherIncludeProduct: 0
      productTypeIdList: []
    isDelete: 0
  dependence_case: false
  dependence_case_data: null
  assert:
    code:
      jsonpath: $.code
      type: ==
      value: 200
      AssertType: null
      message: 接口状态码不为200
    msg:
      jsonpath: $.msg
      type: contains
      value: 成功
      AssertType: null
  sql: null
  setup_sql: null
