case_common:
  allureEpic: 标题：platform-Cloud-Plus微服务权限管理系统_接口文档
  allureFeature: banner配置信息
  allureStory: 查询banner配置信息列表
system_bannerConfigInfo_list_01:
  host: ${{host()}}
  url: /system/bannerConfigInfo/list
  method: POST
  detail: banner配置信息 - 查询banner配置信息列表
  headers:
    Authorization: $cache{app_token}
    Content-Language: zh_CN
    App-Source: WObird
  requestType: json
  is_run: null
  data:
    pageQuery:
      pageSize: 0
      pageNum: 0
      orderByColumn: ''
      isAsc: ''
    paramData:
      appSource: ''
      bannerName: ''
      bannerType: ''
      putOnShelves: 0
      bannerScope: 0
  dependence_case: false
  dependence_case_data: null
  assert:
    code:
      jsonpath: $.code
      type: ==
      value: 200
      AssertType: null
      message: 接口状态码不为200
    msg:
      jsonpath: $.msg
      type: contains
      value: 成功
      AssertType: null
  sql: null
  setup_sql: null
