case_common:
  allureEpic: 标题：platform-Cloud-Plus微服务权限管理系统_接口文档
  allureFeature: 问题反馈工单配置
  allureStory: 查询 问题反馈工单配置 列表
product_feedback_workOrderAssign_list_01:
  host: ${{host()}}
  url: /product/feedback/workOrderAssign/list
  method: POST
  detail: 问题反馈工单配置 - 查询 问题反馈工单配置 列表
  headers:
    Authorization: $cache{app_token}
    Content-Language: zh_CN
    App-Source: WObird
  requestType: json
  is_run: null
  data:
    appSource: ''
    feedbackType: ''
  dependence_case: false
  dependence_case_data: null
  assert:
    code:
      jsonpath: $.code
      type: ==
      value: 200
      AssertType: null
      message: 接口状态码不为200
    msg:
      jsonpath: $.msg
      type: contains
      value: 成功
      AssertType: null
  sql: null
  setup_sql: null
