case_common:
  allureEpic: 标题：platform-Cloud-Plus微服务权限管理系统_接口文档
  allureFeature: 接收数据同步
  allureStory: 同步产品数据
product_syncreceive_putProduct_01:
  host: ${{host()}}
  url: /product/syncreceive/putProduct
  method: POST
  detail: 接收数据同步 - 同步产品数据
  headers:
    Authorization: $cache{app_token}
    Content-Language: zh_CN
    App-Source: WObird
  requestType: json
  is_run: null
  data:
    product:
      createBy: ''
      createTime: 0
      updateBy: ''
      updateTime: 0
      params: {}
      id: 0
      productId: ''
      name: ''
      multNameJson: ''
      configNetworkJson: ''
      categoryId: ''
      typeId: ''
      modelSign: ''
      linkType: 0
      capability: 0
      isPublish: true
      dmsType: 0
      supportGroup: true
      remark: ''
      pic: ''
      picPrefix: ''
      picType: ''
      customerId: 0
      appId: ''
      cloudStorageArea: ''
      cloudStoragePay: 0
    productType:
      createBy: ''
      createTime: 0
      updateBy: ''
      updateTime: 0
      params: {}
      typeId: ''
      categoryId: ''
      name: ''
      egName: ''
      remark: ''
      pic: ''
      picPrefix: ''
      picType: ''
      customerId: 0
      multNameJson: ''
  dependence_case: false
  dependence_case_data: null
  assert:
    code:
      jsonpath: $.code
      type: ==
      value: 200
      AssertType: null
      message: 接口状态码不为200
    msg:
      jsonpath: $.msg
      type: contains
      value: 成功
      AssertType: null
  sql: null
  setup_sql: null
