case_common:
  allureEpic: 标题：platform-Cloud-Plus微服务权限管理系统_接口文档
  allureFeature: 问题反馈工单配置
  allureStory: 修改 问题反馈工单配置
product_feedback_workOrderAssign_01:
  host: ${{host()}}
  url: /product/feedback/workOrderAssign
  method: PUT
  detail: 问题反馈工单配置 - 修改 问题反馈工单配置
  headers:
    Authorization: $cache{app_token}
    Content-Language: zh_CN
    App-Source: WObird
  requestType: json
  is_run: null
  data:
    feedbackWorkOrderAssignId: 0
    assignUserId: 0
    assignUserName: ''
  dependence_case: false
  dependence_case_data: null
  assert:
    code:
      jsonpath: $.code
      type: ==
      value: 200
      AssertType: null
      message: 接口状态码不为200
    msg:
      jsonpath: $.msg
      type: contains
      value: 成功
      AssertType: null
  sql: null
  setup_sql: null
