case_common:
  allureEpic: 标题：platform-Cloud-Plus微服务权限管理系统_接口文档
  allureFeature: 产品类型（第3层）
  allureStory: 查询产品类型列表
product_type_list_01:
  host: ${{host()}}
  url: /product/type/list
  method: GET
  detail: 产品类型（第3层） - 查询产品类型列表
  headers:
    Authorization: $cache{app_token}
    Content-Language: zh_CN
    App-Source: WObird
  requestType: params
  is_run: null
  data:
    bo: $cache{bo}
    pageQuery: $cache{pageQuery}
  dependence_case: false
  dependence_case_data: null
  assert:
    code:
      jsonpath: $.code
      type: ==
      value: 200
      AssertType: null
      message: 接口状态码不为200
    msg:
      jsonpath: $.msg
      type: contains
      value: 成功
      AssertType: null
  sql: null
  setup_sql: null
