case_common:
  allureEpic: 标题：platform-Cloud-Plus微服务权限管理系统_接口文档
  allureFeature: 消息推送方式
  allureStory: 根据推送类型查询消息code
product_pushMethod_queryByType_01:
  host: ${{host()}}
  url: /product/pushMethod/queryByType/$cache$cache{type}/$cache$cache{appSource}
  method: GET
  detail: 消息推送方式 - 根据推送类型查询消息code
  headers:
    Authorization: $cache{app_token}
    Content-Language: zh_CN
    App-Source: WObird
  requestType: null
  is_run: null
  data: {}
  dependence_case: false
  dependence_case_data: null
  assert:
    code:
      jsonpath: $.code
      type: ==
      value: 200
      AssertType: null
      message: 接口状态码不为200
    msg:
      jsonpath: $.msg
      type: contains
      value: 成功
      AssertType: null
  sql: null
  setup_sql: null
