case_common:
  allureEpic: 标题：platform-Cloud-Plus微服务权限管理系统_接口文档
  allureFeature: 品牌品类（第2层）
  allureStory: 获取品牌品类详细信息
product_brandCategory_01:
  host: ${{host()}}
  url: /product/brandCategory/$cache{categoryId}
  method: GET
  detail: 品牌品类（第2层） - 获取品牌品类详细信息
  headers:
    Authorization: $cache{app_token}
    Content-Language: zh_CN
    App-Source: WObird
  requestType: null
  is_run: null
  data: {}
  dependence_case: false
  dependence_case_data: null
  assert:
    code:
      jsonpath: $.code
      type: ==
      value: 200
      AssertType: null
      message: 接口状态码不为200
    msg:
      jsonpath: $.msg
      type: contains
      value: 成功
      AssertType: null
  sql: null
  setup_sql: null
